### ISSUE TITLE
Fails to work in project with Guava 18.0

### ISSUE THREAD

**Issue by harningt** [trajano/caliper#1]
With a project that is using Guava, caliper fails to start with the following stack trace snippet:

```
java.lang.NoSuchMethodError: com.google.common.collect.Multisets.removeOccurrences(Lcom/google/common/collect/Multiset;Lcom/google/common/collect/Multiset;)Z
    at com.google.caliper.runner.ExperimentingRunnerModule.findAllBenchmarkMethods(ExperimentingRunnerModule.java:174)
    at com.google.caliper.runner.ExperimentingRunnerModule.provideInstrumentations(ExperimentingRunnerModule.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
```

**Comment by trajano** [comment]
Looks like it is part of the core caliper code, you can try posting it here too http://code.google.com/p/caliper/issues/list 

I am keeping it open in case I decide to fix it myself.

**Comment by trajano** [comment]
Looking at it more, it seems like you may be using an older version on Guava since the method should exist.  Can you check to ensure that you have no [dependency convergence](http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) issues on your project.

**Comment by trajano** [comment]
I deployed a snapshot build at https://oss.sonatype.org/ see if it works for you if it does I will create a release package.

**Comment by harningt** [comment]
Pulling in the snapshot works great :+1:

Could have also possibly been related to me testing a release version before vs snapshot of a newer codebase.
Regarding dependency convergence... the project 'main' source depends on Guava 18.0 and a few small libraries with no other dependencies (annotation libraries, bit twiddling library)
The test source depends on spock which pulls in groovy and its dependencies (none of which are Guava).

**Comment by trajano** [comment]
Okay i will release in a few days.

**Comment by trajano** [comment]
Release issues because my personal build server wasn't designed to do the caliper unit tests that are memory intensive so I have to tweak their test scripts to ignore it.

**Comment by trajano** [comment]
Fixed in caliper-1.2.1 release to central
